source "https://rubygems.org"

ruby ">= 3.2.0"

gem "rails", "~> 7.1.0"
gem "puma", ">= 5.0"
gem "mongoid", "~> 9.0"
gem "sidekiq", "~> 7.0"
gem "rack-cors"
gem "dotenv-rails"
gem "marcel"
gem "zeitwerk"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "rspec-rails"
end
